fixes #127 Provided service type LoadBalancer
ansible/tower-operator pull request #128
Opened 2021-03-17 12:59 UTC by billett83

Added support for service type LoadBalancer.

2021-03-17 15:06 UTC, shanemcd commented on README.md
> +  tower_ingress_protocal: http
```suggestion
  tower_ingress_protocol: http
```

2021-03-17 15:08 UTC, shanemcd commented on README.md
> +  tower_ingress_type: Loadbalancer
```suggestion
  tower_ingress_type: LoadBalancer
```

2021-03-17 15:08 UTC, shanemcd commented on ansible/instantiate-awx-deployment.yml
> +            tower_ingress_type: "{{ tower_ingress_type | default(omit) }}"  # Either Route, Ingress or Loadbalancer
```suggestion
            tower_ingress_type: "{{ tower_ingress_type | default(omit) }}"  # Either Route, Ingress or LoadBalancer
```

2021-03-17 15:08 UTC, shanemcd commented on ansible/templates/crd.yml.j2
> +                    - Loadbalancer
```suggestion
                    - LoadBalancer
```

2021-03-17 15:08 UTC, shanemcd commented on deploy/awx-operator.yaml
> +                    - Loadbalancer
```suggestion
                    - LoadBalancer
```

2021-03-17 15:09 UTC, shanemcd commented on deploy/crds/awx_v1beta1_crd.yaml
> +                    - Loadbalancer
```suggestion
                    - LoadBalancer
```

2021-03-17 15:10 UTC, shanemcd commented on deploy/olm-catalog/awx-operator/manifests/awx-operator.clusterserviceversion.yaml
> +        - urn:alm:descriptor:com.tectonic.ui:fieldDependency:tower_ingress_type:Loadbalancer
```suggestion
        - urn:alm:descriptor:com.tectonic.ui:fieldDependency:tower_ingress_type:LoadBalancer
```

2021-03-17 15:10 UTC, shanemcd reviewed
Did some nitpicking but overall this is awesome. Thanks for this.

2021-03-18 10:41 UTC, Spredzy requested changes
Minor comments, overall looks good! Thank you.

2021-03-18 10:41 UTC, Spredzy commented on roles/installer/templates/tower_service.yaml.j2
> +{% if tower_ingress_type == "loadbalancer" %}
Missing a `| lower` here

2021-03-18 10:41 UTC, Spredzy commented on deploy/olm-catalog/awx-operator/manifests/awx-operator.clusterserviceversion.yaml
> +        - urn:alm:descriptor:com.tectonic.ui:select:Loadbalancer
s/Loadbalancer/LoadBalancer/

2021-03-18 10:41 UTC, Spredzy commented on deploy/olm-catalog/awx-operator/manifests/awx-operator.clusterserviceversion.yaml
> +        - urn:alm:descriptor:com.tectonic.ui:select:https
Need to add `urn:alm:descriptor:com.tectonic.ui:fieldDependency:tower_ingress_type:LoadBalancer`

2021-03-18 10:41 UTC, Spredzy commented on deploy/olm-catalog/awx-operator/manifests/awx-operator.clusterserviceversion.yaml
> +        - urn:alm:descriptor:com.tectonic.ui:number
Need to add `urn:alm:descriptor:com.tectonic.ui:fieldDependency:tower_ingress_type:LoadBalancer`

2021-03-18 10:41 UTC, Spredzy commented on deploy/olm-catalog/awx-operator/manifests/awx.ansible.com_awxs_crd.yaml
> +                - Loadbalancer
s/Loadbalancer/LoadBalancer/

2021-03-18 10:59 UTC, billett83 commented
Thank you both. I have review and committed your suggested changed @Spredzy

2021-03-18 11:01 UTC, Spredzy commented on deploy/olm-catalog/awx-operator/manifests/awx-operator.clusterserviceversion.yaml
> +        - urn:alm:descriptor:com.tectonic.ui:select:LoadB alancer
nit: extra space here

2021-03-18 11:12 UTC, billett83 commented on deploy/olm-catalog/awx-operator/manifests/awx-operator.clusterserviceversion.yaml
> +        - urn:alm:descriptor:com.tectonic.ui:select:LoadB alancer
Apologies

2021-03-23 10:36 UTC, Spredzy approved these changes
Thank you !

2021-03-23 13:49 UTC, merged