Add websocket configuration for contour ingress
ansible/tower-operator pull request #1320
Opened 2023-04-03 14:44 UTC by lumarel

##### SUMMARY

As described in [this issue](https://github.com/ansible/awx/issues/9747#issuecomment-1440068816), the websocket is not available through contour, as this needs special configuration.
Here is also the [help page](https://projectcontour.io/docs/1.24/config/websockets/) from contour.

##### ISSUE TYPE

 - Bug, Docs Fix or other nominal change

##### ADDITIONAL INFORMATION

So this change basically implements a check if a contour ingress is installed on the cluster, and if yes, adds the websocket route, as well as the seperate path for that.

Unfortunately I wasn't able to spin up the tests, as it looks for be that these are broken somehow, if I can get these working somehow I will gladly run through them!
As well as, if any changes are wanted I will definitely try to improve the contribution.

2023-04-05 18:10 UTC, TheRealHaoLiu requested changes
instead of adding `is_ingress_contour` i think we can add `contour` as a `ingress_type` and use that to trigger the setting

2023-04-05 20:58 UTC, lumarel commented
@TheRealHaoLiu I thought about that in the first place, but refrained from that, because I thought it would be better if it autodetects the ingress controller, but yes sure I am going to rebuild the change to upfront parameter.

One thing I'm just thinking about is in this case if it would be better, to create a dependent `ingress_controller` variable instead of a completely new `ingress_type`, as the latter one will complicate the documentation a lot more.

2023-04-12 18:22 UTC, rooftopcellist commented on roles/installer/templates/networking/ingress.yaml.j2
> +          - path: '{{ ingress_path }}/websocket'
@lumarel hey, could you give us some context for why it is only the `/websocket` path here?

Could you also describe the use case for configuration like this?  I'm not very familiar with Contour and Envoy, thanks ahead of time!

2023-04-12 18:24 UTC, rooftopcellist commented on roles/installer/templates/networking/ingress.yaml.j2
> +          - path: '{{ ingress_path }}/websocket'
Ok, I re-read your description, I understand now, thanks.

2023-04-12 18:24 UTC, rooftopcellist approved these changes

2023-04-12 18:24 UTC, TheRealHaoLiu approved these changes

2023-04-12 18:29 UTC, merged