adding service account image pull secret
ansible/tower-operator pull request #207
Opened 2021-04-13 11:51 UTC by techBeck03

This PR adds an image pull secret to the service account associated with a given AWX deployment.  This helps get around the daily pull limits of docker registries such as DockerHub by allowing a user to use their registered accounts.  The current `tower_image_pull_secret` only applies to awx images and does not apply to images such as `postgres` or `redis`

2021-04-14 02:13 UTC, tchellomello commented
Thanks for your PR @techBeck03, however, there is already a `imagePullSecrets` configured at the deployment level https://github.com/ansible/awx-operator/blob/devel/roles/installer/templates/tower_deployment.yaml.j2#L31-L34 instead of the `serviceAccoutName`. 

I believe the reason why we are doing it at the deployment level instead of the `serviceAccount` one is due to the `serviceAccount` being totally dynamic. 

https://github.com/ansible/awx-operator/blob/devel/roles/installer/templates/tower_service_account.yaml.j2#L1-L11
```yaml
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: '{{ meta.name }}'
  namespace: '{{ meta.namespace }}'
  labels:
    app.kubernetes.io/name: '{{ meta.name }}'
    app.kubernetes.io/part-of: '{{ meta.name }}'
    app.kubernetes.io/managed-by: awx-operator
    app.kubernetes.io/component: awx
```
 and https://github.com/ansible/awx-operator/blob/devel/roles/installer/templates/tower_deployment.yaml.j2#L30
```yaml
      serviceAccountName: '{{ meta.name }}'
```

@techBeck03 was the current implementation not sufficient to address your requirements?

2021-04-14 02:18 UTC, techBeck03 commented
> Thanks for your PR @techBeck03, however, there is already a `imagePullSecrets` configured at the deployment level https://github.com/ansible/awx-operator/blob/devel/roles/installer/templates/tower_deployment.yaml.j2#L31-L34 instead of the `serviceAccoutName`.
> 
> I believe the reason why we are doing it at the deployment level instead of the `serviceAccount` one is due to the `serviceAccount` being totally dynamic.
> 
> https://github.com/ansible/awx-operator/blob/devel/roles/installer/templates/tower_service_account.yaml.j2#L1-L11
> 
> ```yaml
> ---
> apiVersion: v1
> kind: ServiceAccount
> metadata:
>   name: '{{ meta.name }}'
>   namespace: '{{ meta.namespace }}'
>   labels:
>     app.kubernetes.io/name: '{{ meta.name }}'
>     app.kubernetes.io/part-of: '{{ meta.name }}'
>     app.kubernetes.io/managed-by: awx-operator
>     app.kubernetes.io/component: awx
> ```
> 
> and https://github.com/ansible/awx-operator/blob/devel/roles/installer/templates/tower_deployment.yaml.j2#L30
> 
> ```yaml
>       serviceAccountName: '{{ meta.name }}'
> ```
> 
> @techBeck03 was the current implementation not sufficient to address your requirements?

Unfortunately this was not sufficient for me because the current `tower_image_pull_secret` doesn't apply to the `postgres` StatefulSet as mentioned in my initial comment.  If you add the `tower_image_pull_secret` to all image pulls then it would work.

Thanks!

2021-04-14 16:43 UTC, tchellomello commented
@techBeck03 yes, I see where you were going with this. I would say since we already have the `imagePullSecrets` implemented and to avoid having another redundant setting or modify something that would introduce a `break change`, I would just add the `imagePullSecret`  on the `PostgreSQL` deployment. 

Let's see with the others the direction they think we should go, but I think the above would provide the best approach and the least pain. 

Thanks again @techBeck03 !

2021-04-14 16:48 UTC, techBeck03 commented
> @techBeck03 yes, I see where you were going with this. I would say since we already have the `imagePullSecrets` implemented and to avoid having another redundant setting or modify something that would introduce a `break change`, I would just add the `imagePullSecret` on the `PostgreSQL` deployment.
> 
> Let's see with the others the direction they think we should go, but I think the above would provide the best approach and the least pain.
> 
> Thanks again @techBeck03 !

My only other argument for my approach is you wouldn't have to ensure future deployments/statefulsets/etc have the `imagePullSecret` block.  All image pulls would inherit the pull secret from the service account using my proposed changes.  Thanks!

2021-04-21 20:46 UTC, shanemcd commented on README.md
> -* [AWX Operator](#awx-operator)
This makes the diff unnecessarily noisy. Please revert this chunk.

2021-04-21 20:49 UTC, shanemcd commented
Actually, I agree with @tchellomello's points above. Please implement his feedback and we'll get this approved and merged.

2021-04-21 21:37 UTC, tchellomello requested changes
@techBeck03

2021-05-03 17:16 UTC, tchellomello commented
@techBeck03 are you still working on this one?

2021-05-10 02:47 UTC, tchellomello commented
Closing this one as feature has been added at https://github.com/ansible/awx-operator/pull/295

Thanks @techBeck03

2021-05-10 02:47 UTC, closed without merging