Allow tower_ingress_apiversion to be set by the user
ansible/tower-operator pull request #245
Opened 2021-04-24 21:39 UTC by bhundven

In #205, newer ingress is broken by not using networking.k8s.io/v1,
but this may not be the case for all users.

Allow apiVersion to be set by the user.

Default to networking.k8s.io/v1, but add a note in the README.md about
older k8s or ingress-nginx to use networking.k8s.io/v1beta1.

Closes #205

Signed-off-by: Bryan Hundven <bryanhundven@gmail.com>

2021-04-24 21:47 UTC, bhundven commented
@shanemcd lmk if you need any other changes. I'm happy to update this quickly.

2021-04-26 17:12 UTC, shanemcd commented
Unfortunately I don't think it will be so simple. When I tried to use this, I saw:


```
failed: [localhost] (item=tower_ingress) => changed=false
  ansible_loop_var: item
  error: 422
  item: tower_ingress
  msg: 'Failed to apply object: b''{"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"Ingress.extensions \\"awx-ingress\\" is invalid: spec.rules[0].http.paths[0].pathType: Required value: pathType must be specified","reason":"Invalid","details":{"name":"awx-ingress","group":"extensions","kind":"Ingress","causes":[{"reason":"FieldValueRequired","message":"Required value: pathType must be specified","field":"spec.rules[0].http.paths[0].pathType"}]},"code":422}\n'''
  reason: Unprocessable Entity
  status: 422
``` 

Per the k8s docs, it needs to look like this now:


```
spec:
  rules:
    - host: '{{ tower_hostname }}'
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: '{{ meta.name }}-service'
                port:
                  number: 80
```

At which point it will *only* work for `networking.k8s.io/v1`, so there's really no point to make it configurable.

2021-04-26 17:13 UTC, shanemcd commented
I should note that even when I made the above changes I still see the webhook error mentioned in https://github.com/ansible/awx-operator/issues/205

2021-04-26 18:29 UTC, bhundven commented
Well, we can update the template to switch the spec based on which apiVersion is set, but yea... we will have to wait for the next version of minikube.

2021-04-26 18:46 UTC, bhundven commented
I also removed the 'Closes' from the commit message and PR so it doesn't close 205

2021-04-28 15:34 UTC, shanemcd approved these changes
Nice work 😄

2021-04-30 04:10 UTC, tchellomello requested changes
@bhundven thanks for great work.

I would say that would be nice to have this option also exposed as a `hidden` field at https://github.com/ansible/awx-operator/blob/devel/deploy/olm-catalog/awx-operator/manifests/awx-operator.clusterserviceversion.yaml so users can use configure it via UI as well. 

Do you mind adding it for future use? You might need to extend the `awxs.awx.ansible.com` CDR as well. 

But I'm ok if @shanemcd wants to merge like this since we can revisit this if needed in the future.

2021-04-30 21:29 UTC, bhundven commented
I will do that this evening.

2021-04-30 22:35 UTC, bhundven commented
@tchellomello Like that?

2021-05-04 16:35 UTC, bhundven commented
I can't see why test-local molecule scenario is failing. Could I get some help understanding what is going wrong? @shanemcd

2021-05-04 16:49 UTC, bhundven commented
Forgot to add `type: string` to tower_ingress_apiversion in awx_v1beta1_crd.yml. Also rebased against latest devel.
@tchellomello Would you review?

2021-05-04 20:37 UTC, bhundven commented
I dropped the commit to try and fix the molecule int to string conversion warning. I think it broke the pipeline.

2021-05-21 22:19 UTC, bhundven commented
I am not sure why this is looping and never coming up? Is there something in molecule that needs to be updated?

2021-05-24 17:35 UTC, bhundven commented
I ran the test locally, and got this during prepare:
```
TASK [Fetch the kubeconfig] ****************************************************
fatal: [kind-test-local]: FAILED! => {"changed": false, "file": "/root/.kube/config", "msg": "unable to calculate the checksum of the remote file"}
```

2021-05-24 19:45 UTC, bhundven commented
That was fixed with a rebase. Now getting `Failed to find exact match for networking.k8s.io/v1.Ingress by [kind, name, singularName, shortNames]` when set to `extensions/v1beta1`, and `Failed to find exact match for .Ingress by [kind, name, singularName, shortNames]` when set to `networking.k8s.io/v1`. So I'm trying to sort that out now.

2021-05-24 20:10 UTC, bhundven commented
Ok, I fixed that, this passed on my test-local setup.

2021-06-01 20:12 UTC, closed without merging