Add support for custom service labels
ansible/tower-operator pull request #272
Opened 2021-05-03 15:51 UTC by kimbernator

resolves https://github.com/ansible/awx-operator/issues/269

2021-05-03 16:59 UTC, tchellomello requested changes
@kimbernator Thanks for your contribution.. It looks good just a small change to make the attribute class `hidden` . Thanks!

2021-05-03 16:59 UTC, tchellomello commented on deploy/olm-catalog/awx-operator/manifests/awx-operator.clusterserviceversion.yaml
> +        - urn:alm:descriptor:com.tectonic.ui:text
Can you make this field hidden?

2021-05-03 18:12 UTC, kimbernator commented on deploy/olm-catalog/awx-operator/manifests/awx-operator.clusterserviceversion.yaml
> +        - urn:alm:descriptor:com.tectonic.ui:text
Just updated.

2021-05-04 18:19 UTC, kimbernator commented
Requested change has been completed.

2021-05-10 19:10 UTC, rooftopcellist approved these changes

2021-05-10 19:18 UTC, tchellomello approved these changes
:+1:

2021-05-10 19:18 UTC, merged