Add quotes to string type extra_settings
ansible/tower-operator pull request #324
Opened 2021-05-19 07:39 UTC by Zokormazo

This fixes https://github.com/ansible/awx-operator/issues/311 and avoid using `"''"` on the spec file

Signed-off-by: Julen Landa Alustiza <jlanda@redhat.com>

2021-05-19 21:45 UTC, rooftopcellist approved these changes

2021-05-25 15:43 UTC, tchellomello requested changes
@Zokormazo can you rebase your PR so we can merge it? Thanks!

2021-05-26 07:19 UTC, Zokormazo commented
> @Zokormazo can you rebase your PR so we can merge it? Thanks!

Done

2021-05-26 16:02 UTC, tchellomello approved these changes
Thanks @Zokormazo

2021-05-26 16:06 UTC, merged