Define ingress path as variable for deployments
ansible/tower-operator pull request #464
Opened 2021-07-12 04:27 UTC by js-rwwa

This PR provides the ingress path on ingress deployment as a variable that defaults to '/'. By overriding this value, custom ingress can be applied for running on cloud-providers using external LoadBalancers.

For the issue, please see: https://github.com/ansible/awx-operator/issues/455.

Updates the defaults for the installer role, the crd's and the documentation. Tested build against local Kubernetes by updating the ingress_path to be '' and '/'.

2021-07-12 04:29 UTC, MrBones757 commented
The operator has been built locally and deployed as an in-place upgrade to 0.12 - testing addition of this path and param update succeeded on an existing awx cluster

2021-07-14 17:33 UTC, tchellomello requested changes
Thanks so much for your contribution @js-rwwa. I think you just need to address a small thing. 

I can see you manually edited the files because the file `ansible/templates/crd.yml.j2` is not included on your PR. This `ansible/templates/crd.yml.j2` is the source file we use to generate the remaining files to the operator. 

You can use this script `https://github.com/ansible/awx-operator/blob/devel/scripts/generate-files.sh` to generate the changes for you. 

Once this gets addressed, looks good to be merged! 

Thank you!

2021-07-15 00:40 UTC, js-rwwa commented
My apologies @tchellomello , I did miss that in the readme. I have updated ansible/templates/crd.yml.j2 and run the generate-files with TAG=0.12.0.

Could you please review the files to see if anything else needs changing? 

Thank you!

2021-07-25 03:20 UTC, tchellomello approved these changes
Thanks for fixing it @js-rwwa

It looks good to me.  @shanemcd  @rooftopcellist  @Spredzy  can we have another set of eyes on it?

2021-07-26 13:54 UTC, rooftopcellist approved these changes
lgtm, thanks for the contribution @js-rwwa!

2021-07-26 13:54 UTC, merged