feat(readme): add k8s cluster setup instructions
ansible/tower-operator pull request #592
Opened 2021-10-07 12:11 UTC by mrwiora

for those running a k8s cluster, the instructions are not very clear. 
Especially for those ones which were formerly using 0.13 and the deploy/awx-operator.yml file.
This was discussed in issue https://github.com/ansible/awx-operator/issues/582 and this PR adds instructions that helps.

2021-10-07 13:08 UTC, kurokobo commented
Thanks for referring my comment.

In my opinion, if there are both "Basic Install" and "Basic Install on K8S Cluster", users will be confused because minikube is also a kind of "K8S Cluster".

The need to clone and checkout the repo are [already described in "Basic Install" section](https://github.com/ansible/awx-operator/blob/ee2980b8bbfac8c68b217e51d9e676743ecd57b3/README.md?plain=1#L104-L108):
````md
Now you need to deploy AWX Operator into your cluster. Clone this repo and `git checkout` the latest version from https://github.com/ansible/awx-operator/releases, and then run the following command:

```
$ export NAMESPACE=my-namespace
$ make deploy
...
````

Therefore, if you want to make the procedure more detailed, isn't it enough to modify above description and commands, instead of adding a new section?

2021-10-07 16:22 UTC, mrwiora commented
@kurokobo thanks for the hint with the possible confusion - I declared the first as beginners (option 1) and the other one should be obvious for those who know what they do.
As the first one is for beginners it's okay, that the git clone command is explained, for the second it should be fair enough to have the git clone instructions in a code segment.

2021-10-18 21:19 UTC, shanemcd requested changes

2021-10-18 21:19 UTC, shanemcd commented on README.md
> +```bash
For consistent formatting with the rest of the readme, please:

- Remove the `bash` here. 
- Update to look like the other code blocks in this readme (include the `$ ` shell prompts). 
- Please also add a blank newline before the code block.

2021-10-18 21:19 UTC, shanemcd commented on README.md
> +### Basic Install on minikube for beginner or testing
```suggestion
### Basic Install on minikube (beginner or testing)
```

2021-10-18 21:19 UTC, shanemcd commented on README.md
> +### Basic Install on K8S Cluster
```suggestion
### Basic Install on existing cluster
```

2021-10-18 21:19 UTC, shanemcd commented on README.md
> +git checkout 0.14.0
Please remove the hardcoded version and add some kind of placeholder.

2021-10-30 23:45 UTC, mrwiora commented on README.md
> +```bash
thanks man for the review and the suggestions - all applied :)
https://github.com/mrwiora/awx-operator/commit/97a97ded0df2f3c921016aa71e55c145b9ed2a48

2021-10-30 23:45 UTC, mrwiora commented on README.md
> +git checkout 0.14.0
same here
https://github.com/mrwiora/awx-operator/commit/97a97ded0df2f3c921016aa71e55c145b9ed2a48

2022-02-11 22:24 UTC, shanemcd approved these changes

2022-02-11 22:25 UTC, merged