Add runasuser toggle
ansible/tower-operator pull request #643
Opened 2021-11-09 15:40 UTC by gamuniz

add run_userid to allow uniform UID across task and controller-ee

2021-11-09 15:42 UTC, kdelee approved these changes

2021-11-09 22:43 UTC, dsavineau requested changes

2021-11-09 22:43 UTC, dsavineau commented on roles/installer/templates/deployment.yaml.j2
> +{% else %}
running a container with a specific user or with the `privileged` flag aren't exclusive (it's not a xor). You can have a privileged container with a non root user so the `elif` statement doesn't right to me.

2021-11-09 22:43 UTC, dsavineau commented on roles/installer/templates/deployment.yaml.j2
> +{% else %}
What's the purpose of the `else` statement here ? there's nothing to do in this situation so we can drop that statement

2021-11-09 22:49 UTC, gamuniz commented on roles/installer/templates/deployment.yaml.j2
> +{% else %}
I can fix that up, jinja2 isn't my favorite to work out. as for the xor, I didn't want to break existing functionality to fix this for my use-case. If you have a suggestion that works for both. I've never tried setting runasuser and privileged as it seems redundant to use runasuser and privileged: true

2021-11-10 14:36 UTC, pabelanger commented
Is this related to https://github.com/ansible/awx-operator/pull/645 ?

2021-11-10 16:21 UTC, gamuniz commented
closing in favor of #645

2021-11-10 16:21 UTC, closed without merging